model:
  time: 8
  patch_size: 4
  depth: 4

  name: "model-"

data:
  var_cnt: 10
  H: 40
  W: 200

  augment: 32

  path: "./data/processed/monthly_tensor.pt"

train:
  val_size: 320
  batch_size: 32
  subset_size: 4096

  load: "./model/2025-11-25/model-49.pt"
  save: "./model/2025-11-12/"

  epochs: 50

  log_freq: 10

args:
  preprocess: true
  evaluate: false
  delete_logs: true

seed: 23489