model:
  time: 8
  patch_size: 2
  depth: 4
  embed_size: 128

  name: "model-"

data:
  var_cnt: 10
  H: 40
  W: 200
  horizon: 12

  augment: 1
  std: 0.00

  path: "./data/processed/monthly_tensor.pt"
  stats_path: "./data/processed/monthly_tensor_stats.json"

train:
  train_size: 0.9
  batch_size: 16
  subset_size: 512

  load: "./model/2025-11-25/model-64.pt"
  save: "./model/2025-11-15/"

  epochs: 100

  log_freq: 10

args:
  preprocess: true
  evaluate: false
  delete_logs: true

seed: 23489

eval:
  save: "./eval/2025-11-15"
  lead: 12
