model:
  time: 8
  patch_size: 2
  depth: 4
  embed_size: 128

  name: "model-"

data:
  var_cnt: 10
  H: 40
  W: 200
  horizon: 12

  augment: 1

  path: "./data/processed/monthly_tensor.pt"
  stats_path: "./data/processed/monthly_tensor_stats.json"

train:
  train_size: 0.9
  batch_size: 8
  subset_size: 4096

  load: "./model/2025-11-25/model-99.pt"
  save: "./model/2025-11-25/"

  epochs: 100

  log_freq: 10

args:
  preprocess: true
  evaluate: true
  delete_logs: true

seed: 23489

eval:
  save: "./final"
  var: -1
  lead: 12
