model:
  time: 8
  patch_size: 4
  depth: 8

  name: "model-"

data:
  var_cnt: 10
  H: 40
  W: 200

  augment: 32

  path: "./data/processed/monthly_tensor.pt"

train:
  train_size: 0.9
  batch_size: 32
  subset_size: 4096

  load: "./model/2025-11-15/model-99.pt"
  save: "./model/2025-11-25/"

  epochs: 100

  log_freq: 10

args:
  preprocess: true
  evaluate: false
  delete_logs: true

seed: 23489

eval:
  save: "./final"